Use np.asarray() to support numpy 2.0
Since NumPy 2.0 removed np.asfarray function, it should be np.asarray instead. Otherwise, it causes AttributeError like:

```py
AttributeError: `np.asfarray` was removed in the NumPy 2.0 release. Use `np.asarray` with a proper dtype instead.. Did you mean: 'asarray'?
```